name: sedekah
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  font_awesome_flutter: ^10.2.1

  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
