// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsw7ER1QvC4kHUUhykGn_qhqJtB-fSvYw',
    appId: '1:97346705217:web:4f754753939abd5bf173c0',
    messagingSenderId: '97346705217',
    projectId: 'sedekah-7d123',
    authDomain: 'sedekah-7d123.firebaseapp.com',
    storageBucket: 'sedekah-7d123.firebasestorage.app',
    measurementId: 'G-79K1WTSPH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj_hqaed1ENMh1AFhID8NzPXat3ZumfUA',
    appId: '1:97346705217:android:6bda84f3a81265d5f173c0',
    messagingSenderId: '97346705217',
    projectId: 'sedekah-7d123',
    storageBucket: 'sedekah-7d123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaxUvsrnuaJmO6chAGQFz5mmvo2UbEqoA',
    appId: '1:97346705217:ios:c130f117d1a9c617f173c0',
    messagingSenderId: '97346705217',
    projectId: 'sedekah-7d123',
    storageBucket: 'sedekah-7d123.firebasestorage.app',
    iosBundleId: 'com.example.sedekah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaxUvsrnuaJmO6chAGQFz5mmvo2UbEqoA',
    appId: '1:97346705217:ios:c130f117d1a9c617f173c0',
    messagingSenderId: '97346705217',
    projectId: 'sedekah-7d123',
    storageBucket: 'sedekah-7d123.firebasestorage.app',
    iosBundleId: 'com.example.sedekah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsw7ER1QvC4kHUUhykGn_qhqJtB-fSvYw',
    appId: '1:97346705217:web:afb74f2764f9f1d1f173c0',
    messagingSenderId: '97346705217',
    projectId: 'sedekah-7d123',
    authDomain: 'sedekah-7d123.firebaseapp.com',
    storageBucket: 'sedekah-7d123.firebasestorage.app',
    measurementId: 'G-0WPYTBY2S4',
  );

}